server:
  port: 8081

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: Config-server
